# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discover', '0002_auto_20170110_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='user_id',
            field=models.CharField(max_length=20),
        ),
    ]
