# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discover', '0003_auto_20170110_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='user_date',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='user_time',
        ),
    ]
